<?php _view__extends('layouts/app')?>

<?php function content() { ?>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">Dashboard</div>

                    <div class="card-body">
                        <?php if (_get_flash('status')) { ?>
                            <div class="alert alert-success" role="alert">
                                <?= _get_flash('status') ?>
                            </div>
                        <?php } ?>

                        You are logged in!
                    </div>
                </div>
            </div>
        </div>
    </div>
<?php }