<?php view__extends('layouts/app') ?>

<?php function content() { ?>
    <div class="flex-center position-ref full-height">

        <div class="content">
            <div class="title m-b-md">
                MPPHP
            </div>

            <div class="links">
                <a href="#">Docs</a>
                <a href="#">News</a>
                <a href="#">Blog</a>
                <a href="https://mpphp.github.io/mpphp">GitHub</a>
            </div>
        </div>
    </div>
<?php } ?> 