<!doctype html>
<html class="no-js" lang="">

<head>
  <meta charset="utf-8">
  <title></title>
  <meta name="description" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="manifest" href="site.webmanifest">
  <link rel="apple-touch-icon" href="icon.png">
  <!-- Place favicon.ico in the root directory -->

  <link rel="stylesheet" href="<?=_asset('/css/normalize.css')?>">
  <link rel="stylesheet" href="<?=_asset('/css/main.css')?>">
  <style>

            * {
                line-height: 1.2;
                margin: 0;
            }

            html {
                color: #888;
                display: table;
                font-family: sans-serif;
                height: 100%;
                text-align: center;
                width: 100%;
            }

            body {
                display: table-cell;
                vertical-align: middle;
                margin: 2em auto;
            }

            h1 {
                color: #555;
                font-size: 2em;
                font-weight: 400;
            }

            p {
                margin: 0 auto;
                width: 280px;
            }

            @media only screen and (max-width: 280px) {

                body, p {
                    width: 95%;
                }

                h1 {
                    font-size: 1.5em;
                    margin: 0 0 0.3em;
                }

            }

        </style>

  <meta name="theme-color" content="#fafafa">
</head>

<body>
  <!--[if IE]>
    <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="https://browsehappy.com/">upgrade your browser</a> to improve your experience and security.</p>
  <![endif]-->

  <!-- Add your site or application content here -->
  <?php view__nests('content') ?>

  <script src="<?=_asset('/js/vendor/modernizr-3.7.1.min.js')?>"></script>
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script>window.jQuery || document.write('<script src="<?=_asset('/js/vendor/jquery-3.3.1.min.js')?>"><\/script>')</script>
  <script src="<?=_asset('/js/plugins.js')?>"></script>
  <script src="<?=_asset('/js/main.js')?>"></script>

  <!-- Google Analytics: change UA-XXXXX-Y to be your site's ID. -->
  <script>
    window.ga = function () { ga.q.push(arguments) }; ga.q = []; ga.l = +new Date;
    ga('create', 'UA-XXXXX-Y', 'auto'); ga('set','transport','beacon'); ga('send', 'pageview')
  </script>
  <script src="https://www.google-analytics.com/analytics.js" async defer></script>
</body>

</html>
